### ISSUE TITLE
Diff from 1st June update

### ISSUE THREAD

**Issue by benravetta** [eddiesigner/weiss-pro#11]
Hi Eddie,

Just noticed theme was updated 1st June, I didn't receive notification of this, am I supposed to?

Is there a way I can see the changes from this update, a diff file or something, so I can implement them myself?

Thanks again.

**Comment by eddiesigner** [comment]
Hi,

Don't worry, that was a small update with some improvements in [the documentation](https://github.com/eddiesigner/weiss-pro/wiki/How-to-enable-the-Members-feature), that's why you didn't receive a notification.

Cheers.

**Comment by eddiesigner** [comment]
I just wanted to let you know that I just released a new version (1.5.0), you can find the diffs in the [releases page](https://github.com/eddiesigner/weiss-pro/releases/tag/v1.5.0).

Keep in mind that the changes are quite a lot because it's a major release, you may want to apply your changes to this version instead of integrating this new version into your current theme.
