### ISSUE TITLE
Add Instagram social link

### ISSUE THREAD

**Issue by gatzka** [eddiesigner/weiss-pro#13]
It would be great to have a  social link to Instagram just like already implemented for Twitter and Facebook.
Would be super nice to have the for authors, posts and pages.

**Comment by eddiesigner** [comment]
Hi 👋🏻

First of all thanks for your purchase!

Currently Ghost only supports Facebook and Twitter natively, that's why the theme only provides links for those social networks. In order to add a link for Instagram, you would need to make a few changes in the templates and add it manually.

Although, for author pages would be specially difficult because their content is generated dinamically based on the author info that comes from the Admin panel where there is no place to add a link for Instagram.

If you still want to add an Instagram link somewhere, you can use something like this:

```html
<a href="https://instagram.com/YOUR_USERNAME" alt="Instagram">
  <span class="icon-instagram" aria-hidden="true"></span>
</a>
```

**Comment by gatzka** [comment]
Hi!

Thanks for your answer. Because the site I'm managing ist single-author, I can probably to as you suggested.

Thanks again.
