### ISSUE TITLE
More social media icons

### ISSUE THREAD

**Issue by Daniel-Madsen** [eddiesigner/weiss-pro#3]
Would it be possible to add instagram and youtube icons to the theme? I would like to add social links for these platforms, but it seems like the icons for these platforms are not included.

**Comment by eddiesigner** [comment]
Hi 👋🏼

First of all thanks for purchasing the theme!

Now, the thing is that Ghost does only support Facebook and Twitter, that's why I don't include more icons. If you want to add more social media links, then you have to modify a bit the templates of the footer and the mobile menu by yourself.

I can include more icons so you can add those links to the footer and to the mobile menu.

**Comment by Daniel-Madsen** [comment]
Hi Eddie

Thank you for your response. I would appreciate if you included them. I'm aware that I will have to do the part myself - I hope the Ghost team will support them natively in the future. Thank you!

**Comment by eddiesigner** [comment]
Hi Daniel,

I will 👍  Just wait for a couple of days, I will release a new version with a few new features, some changes and small bugfixes, this version will include more social icons as well.

Cheers.

**Comment by eddiesigner** [comment]
I just released a new version which includes more social icons (Youtube and Instagram as well) :)
