### ISSUE TITLE
Emails don't send when free member signup is disabled

### ISSUE THREAD

**Issue by FarazPatankar** [eddiesigner/weiss-pro#5]
Hey @eddiesigner,

I purchased this theme today and got everything set up and everything seems to be working fine except this.

When I disabled free member signup and try to signup or sign in, I see the success message but I don't receive an email. I even checked my Mailgun setup and no requests are being sent to Mailgun.

Are you already aware of this/working on it?

**Comment by eddiesigner** [comment]
Hey 👋🏻

First of all thank you for purchasing the theme!

According to [the docs](https://ghost.org/docs/members/patreon/#disable-free-member-signup), if you disable that option the only way people will be able to signup/signin is if they have been imported via an integration with Patreon or other members list.

I guess there is a bug on their side because if you see the success message that means the form action actually returned a succeded response even though Ghost didn't send an email because that option was disabled. Btw, the theme is not responsible of sending those emails, Ghost provides [subscriptions forms](https://ghost.org/docs/members/signup-signin-forms/#subscription-forms) for that purpose and everything is handleded by the platform, not by the theme.

I would suggest enabling that option unless you want to create members only via an integration.

Cheers.

**Comment by FarazPatankar** [comment]
Hmm okay. I've turned it back on for now and everything seems to be working fine. You can close this if you'd like because I am going to go ahead with that flow for now!
