### ISSUE TITLE
CTA is wrong on paid member only posts

### ISSUE THREAD

**Issue by FarazPatankar** [eddiesigner/weiss-pro#6]
So if I create a post that is visible only to members who have paid for a subscription, free members see the wrong CTA.

Instead of prompting them to upgrade their account by taking them to the account page, the theme asks them to sign in or sign up even though they're already logged in.

![wrong-cta](https://user-images.githubusercontent.com/10681116/82519006-a1764c80-9aee-11ea-8164-bd4019701904.jpeg)

**Comment by eddiesigner** [comment]
Thanks for the heads up! I will fix it as soon as possible.

**Comment by FarazPatankar** [comment]
Awesome, let me know once you do that.

Also, how do updates work? I have a few changes I want to make to the theme but it'd be nice to receive updates as well.

Is there a git workflow we could follow where I could just fork and then keep my fork updated with the upstream branch?

**Comment by eddiesigner** [comment]
It's already fixed 👍 

Usually you get an email when the theme is updated, after that you can go to the store where you bought it to download the latest version. If you bought it on Gumroad you can get the latest version right now but if you bought it on ThemeForest then you have to wait one or two days until they approve the update.

There is not a git workflow because a public repository is not available, what I can include in future updates is an url where you can see the diff, for example, this is the diff for the latest changes: https://diffy.org/diff/gqdh36hu6nglabbrog3qh0k9

**Comment by FarazPatankar** [comment]
This is great!

Thanks for the quick fix and also for providing the diff. :)
