### ISSUE TITLE
Changing dropdown second nav. to icons

### ISSUE THREAD

**Issue by benravetta** [eddiesigner/weiss-pro#8]
Hi, just wondering how I can get rid of the more menu and have a social icon list much like Casper default has. Instead of labels. I tried to implement it here, but I'm guessing I have to modify something in the header.

**Comment by eddiesigner** [comment]
Hi,

I would recommend to keep the "More" button since is the only way to access to the big sumenu that appears when you click on it. If you still want to remove it then you should open the file `partials/header.hbs` with a text editor and remove the code from line 110 to line 114:

```hbs
<li class="m-nav-item no-effect js-anime">
  <button class="m-more-button in-desktop-menu js-toggle-submenu" aria-label="Open submenu">
    <span class="icon-dots"></span>
  </button>
</li>
```

What social links would you like to use? This theme comes with the following social icons ready to use:

* facebook
* twitter
* youtube
* pinterest
* linkedin
* instagram
* github
* behance
* snapchat
* discord
* deviantart
* wechat
* tumblr
* tiktok
* soundcloud
* telegram
* spotify
* rss
* vimeo
* steam
* vk
* imdb

To use any of them you just need to create a `span` element with the class `icon-SOCIAL_ICON`, for example:

```html
<span class="icon-facebook"></span>
```

If you want to add social links in the menu then you have to open the file `partials/header.hbs` with a text editor and add (exactly where you deleted the "More button" code) something like this for each social link you want:

```hbs
<!-- Facebook example -->
<li class="m-nav-item no-effect js-anime">
  <a href="YOUR_FACEBOOK_URL">
    <span class="icon-facebook"></span>
  </a>
</li>
```

**Comment by benravetta** [comment]
Hi Eddie,

Thanks for this. I wouldn’t mind keeping the more menu, but perhaps utilising it for something else. Is this a possibility? Could I choose to display the social icons beside the more menu?

Also, is it possible to modify the second nav in the footer to include icons instead of labels?

I would only be using perhaps 8 icons (Twitter, Instagram, Facebook, YouTube, LinkedIn, Github, Snapchat and a custom icon for my company website)

Best Wishes,
Ben Ravetta

**Comment by eddiesigner** [comment]
Sure, you can have the social icons next to that button. Instead of removing the code I just told you, simply add that code snippet for each social link after the line 109.

If you want to show social links in the second nav of the footer you can open the file `partials/footer.hbs` and replace the following piece of code (lines 16 - 20):

```hbs
{{#if @site.secondary_navigation}}
  <nav class="m-footer__nav-secondary">
    {{navigation type="secondary"}}
  </nav>
{{/if}}
```

with something like this:

```hbs
<li class="m-nav-item" role="menuitem">
  <a href="YOUR_TWITTER_URL">
    <span class="icon-twitter"></span>
  </a>
</li>
<li class="m-nav-item" role="menuitem">
  <a href="YOUR_INSTAGRAM_URL">
    <span class="icon-instagram"></span>
  </a>
</li>
<!-- more social links... -->
```

**Comment by benravetta** [comment]
Hi Eddie,

Thanks for replying. The line at 109 is the wrong place, this is before the 3 dot menu. I want to add the icons in at 118 (in header.hbs) but when I do this with the code you provided, the icon wasn’t responsive with dark/light mode and also had a bulletpoint next to it as an unordered list would. Which class do I need to use to ensure this displays correctly?

Thanks again.

Best Wishes,
Ben Ravetta

**Comment by benravetta** [comment]
You can add in the code yourself if you can fork the project, I've put it in Github. Let me know when you need a pull?

**Comment by eddiesigner** [comment]
If you want to add the icons on that side then you have to add them after line 118 like this:

```hbs
<a href="YOUR_TWITTER_URL" class="m-icon-link">
  <span class="icon-twitter"></span>
</a>
<a href="YOUR_GITHUB_URL" class="m-icon-link">
  <span class="icon-github"></span>
</a>
<!-- more links... -->
```

Since there is no class for those links you also have to go to _Admin panel -> Code injection_ and inject the following code into the _Site Header section_:

```html
<style>
.m-icon-link {
  display: inline-block;
  color: var(--primary-foreground-color);
  font-size: 0.875rem;
  margin: 0 10px;
}

.m-icon-link span {
  color: inherit;
}
</style>
```

**Comment by benravetta** [comment]
Thanks Eddie,

I created a class much like the footer icons, into app.css. Is there a better way to do this?

Best Wishes,
Ben Ravetta

**Comment by eddiesigner** [comment]
In general you should avoid adding styles in that file because whenever the theme gets updated that file will be overwritten.

The best way to add custom styles is by adding them in the Admin panel so they can be persisted.

Another option is to create a custom version of this theme and add your custom styles in the source files (`/src/sass/app.scss` for example) and then build your customized theme.

You can follow this guide to know how to do it: https://github.com/eddiesigner/weiss-pro/wiki/Theme-development-with-Docker

**Comment by benravetta** [comment]
Hi Eddie,

I wish I did this at the start, I have already added so much custom code.
